FROM browserless/base:latest

WORKDIR /opt

COPY features/ /opt/features
COPY utils/ /opt/utils
COPY modules.js /opt
COPY env.js /opt
COPY hooks.js /opt
COPY devRunner.sh /opt
COPY prodRunner.sh /opt
COPY package-lock.json /opt
COPY package.json /opt
COPY protractor.conf.js /opt
COPY RequestsDebugger-Linux-x64 /opt

ARG BROWSERSTACK_USERNAME
ENV BROWSERSTACK_USERNAME=${BROWSERSTACK_USERNAME}

ARG BROWSERSTACK_ACCESS_KEY
ENV BROWSERSTACK_ACCESS_KEY=${BROWSERSTACK_ACCESS_KEY}

ARG DEV_API_KEY
ENV DEV_API_KEY=${DEV_API_KEY}

ARG PROD_API_KEY
ENV PROD_API_KEY=${PROD_API_KEY}

ARG DEV_DELETE_KEY
ENV DEV_DELETE_KEY=${DEV_DELETE_KEY}

ARG PROD_DELETE_KEY
ENV PROD_DELETE_KEY=${PROD_DELETE_KEY}

ARG UWP1_EMAIL
ENV UWP1_EMAIL=${UWP1_EMAIL}

ARG UWP1_PASSWORD
ENV UWP1_PASSWORD=${UWP1_PASSWORD}

RUN npm install